import { useQuery } from 'react-query';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { HiOutlineArrowLeft } from 'react-icons/hi';
import { FiDownload } from 'react-icons/fi';
import { useState } from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { marksApi } from '../api';
import { EventReportCard, AnnualReportCard } from '../types';
import { useAppContext } from '../../../providers/AppContext';
import { getCurrentSchool } from '../../../api/school';

// ── Mode A: Event Report Card ─────────────────────────────────────────────────

function EventReportCardView({ data, schoolName }: { data: EventReportCard; schoolName: string }) {
  const [pdfLoading, setPdfLoading] = useState(false);
  const { examEvent, students, subjects } = data;

  const getMarkForStudent = (subject: EventReportCard['subjects'][number], studentId: number) => {
    return subject.marks.find(m => m.studentId === studentId);
  };

  const downloadPDF = async () => {
    setPdfLoading(true);
    try {
      const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
      const pageW = doc.internal.pageSize.getWidth();
      const M = 10;
      const Navy: [number, number, number] = [15, 52, 96];
      const White: [number, number, number] = [255, 255, 255];
      const Gray100: [number, number, number] = [241, 245, 249];
      const Gray400: [number, number, number] = [148, 163, 184];
      const Gray700: [number, number, number] = [51, 65, 85];

      // Header
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(...Navy);
      doc.text(schoolName.toUpperCase(), pageW / 2, M + 6, { align: 'center' });
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...Gray700);
      doc.text(`${examEvent.name} — Report Card`, pageW / 2, M + 13, { align: 'center' });
      doc.setDrawColor(...Navy);
      doc.setLineWidth(0.5);
      doc.line(M, M + 17, pageW - M, M + 17);

      // Build table: rows = students, cols = subjects
      const head = [['#', 'Student', ...subjects.map(s => `${s.subjectName}\n(${s.totalMarks})`), 'Total', '%']];
      const body = students.map((student, idx) => {
        let obtained = 0;
        let total = 0;
        const subjectCells = subjects.map(subject => {
          const mark = getMarkForStudent(subject, student.studentId);
          if (!mark || mark.isAbsent) return 'AB';
          if (mark.marksObtained === null) return '—';
          obtained += mark.marksObtained;
          total += subject.totalMarks;
          return String(mark.marksObtained);
        });
        const pct = total > 0 ? `${((obtained / total) * 100).toFixed(1)}%` : '—';
        return [String(idx + 1), student.studentName, ...subjectCells, String(obtained), pct];
      });

      autoTable(doc, {
        startY: M + 22,
        margin: { left: M, right: M },
        head,
        body,
        headStyles: { fillColor: Navy, textColor: White, fontSize: 7, fontStyle: 'bold', cellPadding: 2 },
        bodyStyles: { fontSize: 7.5, cellPadding: 2, textColor: Gray700 },
        alternateRowStyles: { fillColor: Gray100 },
        columnStyles: { 0: { cellWidth: 8 }, 1: { cellWidth: 40 } },
        tableLineColor: [226, 232, 240],
        tableLineWidth: 0.2,
      });

      const finalY = (doc as any).lastAutoTable.finalY;
      doc.setFontSize(7);
      doc.setTextColor(...Gray400);
      doc.text('Generated by Al-Sufiaan School Management System', M, finalY + 8);

      const safe = (s: string) => s.replace(/[^a-zA-Z0-9]/g, '_');
      doc.save(`ReportCard_${safe(examEvent.name)}_${new Date().toISOString().slice(0, 10)}.pdf`);
    } finally {
      setPdfLoading(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold text-gray-900">{examEvent.name}</h2>
          <p className="text-sm text-gray-500">{students.length} students · {subjects.length} subjects</p>
        </div>
        <button
          onClick={downloadPDF}
          disabled={pdfLoading}
          className="flex items-center gap-1.5 px-3 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg hover:bg-blue-700 disabled:opacity-50 transition"
        >
          {pdfLoading
            ? <span className="w-3 h-3 border-2 border-white border-t-transparent rounded-full animate-spin" />
            : <FiDownload size={13} />}
          {pdfLoading ? 'Generating…' : 'Download PDF'}
        </button>
      </div>

      <div className="bg-white rounded-xl border border-gray-200 overflow-x-auto">
        <table className="min-w-full divide-y divide-gray-100 text-sm">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase whitespace-nowrap">#</th>
              <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase whitespace-nowrap">Student</th>
              {subjects.map(s => (
                <th key={s.subjectId} className="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase whitespace-nowrap">
                  {s.subjectName}
                  <span className="block text-gray-400 font-normal normal-case">/{s.totalMarks}</span>
                </th>
              ))}
              <th className="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase whitespace-nowrap">Total</th>
              <th className="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase whitespace-nowrap">%</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {students.map((student, idx) => {
              let obtained = 0;
              let total = 0;
              const cells = subjects.map(subject => {
                const mark = getMarkForStudent(subject, student.studentId);
                if (!mark || mark.isAbsent) {
                  return <td key={subject.subjectId} className="px-4 py-2.5 text-center text-xs text-amber-600 font-medium">AB</td>;
                }
                if (mark.marksObtained === null) {
                  return <td key={subject.subjectId} className="px-4 py-2.5 text-center text-xs text-gray-400">—</td>;
                }
                const passed = mark.marksObtained >= subject.passingMarks;
                obtained += mark.marksObtained;
                total += subject.totalMarks;
                return (
                  <td key={subject.subjectId} className={`px-4 py-2.5 text-center text-xs font-medium ${passed ? 'text-gray-800' : 'text-red-600'}`}>
                    {mark.marksObtained}
                  </td>
                );
              });
              const pct = total > 0 ? ((obtained / total) * 100).toFixed(1) : null;
              return (
                <tr key={student.studentId} className="hover:bg-gray-50">
                  <td className="px-4 py-2.5 text-xs text-gray-400">{idx + 1}</td>
                  <td className="px-4 py-2.5 text-sm font-semibold text-gray-800 whitespace-nowrap">{student.studentName}</td>
                  {cells}
                  <td className="px-4 py-2.5 text-center text-sm font-bold text-gray-900">{obtained}</td>
                  <td className="px-4 py-2.5 text-center text-sm font-bold text-blue-600">{pct ? `${pct}%` : '—'}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ── Mode B: Annual Report Card ────────────────────────────────────────────────

function AnnualReportCardView({ data, schoolName }: { data: AnnualReportCard; schoolName: string }) {
  const [pdfLoading, setPdfLoading] = useState(false);
  const { student, enrollment, examEvents, subjects } = data;
  const studentName = `${student.firstName} ${student.lastName}`;

  const downloadPDF = async () => {
    setPdfLoading(true);
    try {
      const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
      const pageW = doc.internal.pageSize.getWidth();
      const M = 10;
      const Navy: [number, number, number] = [15, 52, 96];
      const White: [number, number, number] = [255, 255, 255];
      const Gray100: [number, number, number] = [241, 245, 249];
      const Gray400: [number, number, number] = [148, 163, 184];
      const Gray700: [number, number, number] = [51, 65, 85];

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(...Navy);
      doc.text(schoolName.toUpperCase(), pageW / 2, M + 6, { align: 'center' });
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...Gray700);
      doc.text(`Annual Report Card — ${studentName}  |  ${enrollment.class.name} ${enrollment.section.name}`, pageW / 2, M + 13, { align: 'center' });
      doc.setDrawColor(...Navy);
      doc.setLineWidth(0.5);
      doc.line(M, M + 17, pageW - M, M + 17);

      const head = [['Subject', 'Class Tests (Avg %)', ...examEvents.map(e => e.name)]];
      const body = subjects.map(sub => {
        const ctAvg = sub.classTestAvg.percentage !== null
          ? `${sub.classTestAvg.percentage.toFixed(1)}%`
          : '—';
        const eventCells = examEvents.map(ev => {
          const res = sub.examEvents.find(e => e.eventId === ev.id);
          if (!res || res.totalMarks === null) return '—';
          if (res.isAbsent) return 'AB';
          if (res.marksObtained === null) return '—';
          return `${res.marksObtained}/${res.totalMarks}`;
        });
        return [sub.subjectName, ctAvg, ...eventCells];
      });

      autoTable(doc, {
        startY: M + 22,
        margin: { left: M, right: M },
        head,
        body,
        headStyles: { fillColor: Navy, textColor: White, fontSize: 7.5, fontStyle: 'bold', cellPadding: 2.5 },
        bodyStyles: { fontSize: 8, cellPadding: 2.5, textColor: Gray700 },
        alternateRowStyles: { fillColor: Gray100 },
        columnStyles: { 0: { cellWidth: 45 }, 1: { cellWidth: 30, halign: 'center' } },
        tableLineColor: [226, 232, 240],
        tableLineWidth: 0.2,
      });

      const finalY = (doc as any).lastAutoTable.finalY;
      doc.setFontSize(7);
      doc.setTextColor(...Gray400);
      doc.text('Generated by Al-Sufiaan School Management System', M, finalY + 8);

      const safe = (s: string) => s.replace(/[^a-zA-Z0-9]/g, '_');
      doc.save(`Annual_${safe(studentName)}_${new Date().toISOString().slice(0, 10)}.pdf`);
    } finally {
      setPdfLoading(false);
    }
  };

  return (
    <div className="space-y-4">
      {/* Student info */}
      <div className="bg-white rounded-xl border border-gray-200 p-5 flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold text-gray-900">{studentName}</h2>
          <p className="text-sm text-gray-500 mt-0.5">
            {enrollment.class.name} · {enrollment.section.name}
            {enrollment.rollNumber ? ` · Roll ${enrollment.rollNumber}` : ''}
          </p>
        </div>
        <button
          onClick={downloadPDF}
          disabled={pdfLoading}
          className="flex items-center gap-1.5 px-3 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg hover:bg-blue-700 disabled:opacity-50 transition"
        >
          {pdfLoading
            ? <span className="w-3 h-3 border-2 border-white border-t-transparent rounded-full animate-spin" />
            : <FiDownload size={13} />}
          {pdfLoading ? 'Generating…' : 'Download PDF'}
        </button>
      </div>

      {/* Annual table */}
      <div className="bg-white rounded-xl border border-gray-200 overflow-x-auto">
        <table className="min-w-full divide-y divide-gray-100 text-sm">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Subject</th>
              <th className="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase whitespace-nowrap">Class Tests<span className="block font-normal normal-case text-gray-400">Avg %</span></th>
              {examEvents.map(ev => (
                <th key={ev.id} className="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase whitespace-nowrap">{ev.name}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {subjects.map(sub => (
              <tr key={sub.subjectId} className="hover:bg-gray-50">
                <td className="px-4 py-3 text-sm font-semibold text-gray-800">{sub.subjectName}</td>
                <td className="px-4 py-3 text-center">
                  {sub.classTestAvg.percentage !== null ? (
                    <span className={`text-sm font-bold ${sub.classTestAvg.percentage >= 50 ? 'text-emerald-600' : 'text-red-600'}`}>
                      {sub.classTestAvg.percentage.toFixed(1)}%
                    </span>
                  ) : (
                    <span className="text-xs text-gray-400">—</span>
                  )}
                </td>
                {examEvents.map(ev => {
                  const res = sub.examEvents.find(e => e.eventId === ev.id);
                  if (!res || res.totalMarks === null) {
                    return <td key={ev.id} className="px-4 py-3 text-center text-xs text-gray-400">—</td>;
                  }
                  if (res.isAbsent) {
                    return <td key={ev.id} className="px-4 py-3 text-center text-xs text-amber-600 font-medium">Absent</td>;
                  }
                  if (res.marksObtained === null) {
                    return <td key={ev.id} className="px-4 py-3 text-center text-xs text-gray-400">—</td>;
                  }
                  const passed = res.passingMarks !== null && res.marksObtained >= res.passingMarks;
                  return (
                    <td key={ev.id} className="px-4 py-3 text-center">
                      <span className={`text-sm font-bold ${passed ? 'text-gray-800' : 'text-red-600'}`}>
                        {res.marksObtained}
                      </span>
                      <span className="text-xs text-gray-400">/{res.totalMarks}</span>
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ── Main Page ─────────────────────────────────────────────────────────────────

export default function ReportCardPage() {
  const { showToast } = useAppContext();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const examEventId = searchParams.get('examEventId') ? Number(searchParams.get('examEventId')) : null;
  const classId     = searchParams.get('classId')     ? Number(searchParams.get('classId'))     : null;
  const sectionId   = searchParams.get('sectionId')   ? Number(searchParams.get('sectionId'))   : null;
  const sessionId   = searchParams.get('sessionId')   ? Number(searchParams.get('sessionId'))   : null;
  const studentId   = searchParams.get('studentId')   ? Number(searchParams.get('studentId'))   : null;

  const isEventMode  = !!examEventId && !!classId && !!sectionId && !!sessionId;
  const isAnnualMode = !!studentId && !!sessionId;

  const { data: school } = useQuery('currentSchool', getCurrentSchool, { staleTime: 10 * 60 * 1000 });
  const schoolName = school?.name ?? 'Al-Sufiaan School';

  const { data: eventReport, isLoading: eventLoading } = useQuery<EventReportCard>(
    ['report-card-event', examEventId, classId, sectionId, sessionId],
    () => marksApi.getEventReportCard(examEventId!, classId!, sectionId!, sessionId!),
    {
      enabled: isEventMode,
      onError: (e: unknown) => showToast({ message: (e as Error).message, type: 'ERROR' }),
    }
  );

  const { data: annualReport, isLoading: annualLoading } = useQuery<AnnualReportCard>(
    ['report-card-annual', studentId, sessionId],
    () => marksApi.getAnnualReportCard(studentId!, sessionId!),
    {
      enabled: isAnnualMode,
      onError: (e: unknown) => showToast({ message: (e as Error).message, type: 'ERROR' }),
    }
  );

  const isLoading = eventLoading || annualLoading;

  if (!isEventMode && !isAnnualMode) {
    return (
      <div className="p-4 md:p-8 bg-gray-50 min-h-screen flex items-center justify-center">
        <div className="bg-white rounded-xl border border-gray-200 p-12 text-center">
          <p className="text-gray-500 mb-3">Missing required parameters.</p>
          <button onClick={() => navigate(-1)} className="text-blue-600 hover:underline text-sm">Go back</button>
        </div>
      </div>
    );
  }

  return (
    <div className="p-4 md:p-8 bg-gray-50 min-h-screen">
      <div className="max-w-7xl mx-auto space-y-6">

        {/* Header */}
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate(-1)}
            className="p-2 text-gray-400 hover:text-gray-600 hover:bg-white border border-transparent hover:border-gray-200 rounded-lg transition"
          >
            <HiOutlineArrowLeft className="text-lg" />
          </button>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">
              {isEventMode ? 'Event Report Card' : 'Annual Report Card'}
            </h1>
            <p className="text-sm text-gray-500 mt-0.5">
              {isEventMode ? 'Class-wide marks summary for this exam event' : 'Full-year academic summary for this student'}
            </p>
          </div>
        </div>

        {isLoading ? (
          <div className="flex justify-center items-center h-64">
            <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600" />
          </div>
        ) : isEventMode && eventReport ? (
          <EventReportCardView data={eventReport} schoolName={schoolName} />
        ) : isAnnualMode && annualReport ? (
          <AnnualReportCardView data={annualReport} schoolName={schoolName} />
        ) : (
          <div className="bg-white rounded-xl border border-gray-200 py-20 text-center">
            <p className="text-gray-500">No data available.</p>
          </div>
        )}
      </div>
    </div>
  );
}
